org.gradle.jvmargs=-Xmx3G -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -Dhttp.nonProxyHosts=localhost|127.0.0.1
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.172
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=neko_tlm_bridge
mod_name=N.E.K.OxTLM
mod_license=MIT
mod_version=1.0.7
mod_group_id=com.neko_tlm_bridge
mod_authors=ggg233m
mod_description=Bridge mod connecting TouhouLittleMaid with N.E.K.O AI platform
